[
	{
		"1. symbol": "D",
		"2. name": "Dominion Energy Inc",
		"3. type": "Equity",
		"4. region": "United States",
		"5. marketOpen": "09:30",
		"6. marketClose": "16:00",
		"7. timezone": "UTC-04",
		"8. currency": "USD",
		"9. matchScore": "1.0000",
	},
	{
		"1. symbol": "D00.FRK",
		"2. name": "Dometic Group AB (publ)",
		"3. type": "Equity",
		"4. region": "Frankfurt",
		"5. marketOpen": "08:00",
		"6. marketClose": "20:00",
		"7. timezone": "UTC+02",
		"8. currency": "EUR",
		"9. matchScore": "0.3333",
	},
	{
		"1. symbol": "D05.FRK",
		"2. name": "Deciphera Pharmaceuticals Inc",
		"3. type": "Equity",
		"4. region": "Frankfurt",
		"5. marketOpen": "08:00",
		"6. marketClose": "20:00",
		"7. timezone": "UTC+02",
		"8. currency": "EUR",
		"9. matchScore": "0.3333",
	},
	{
		"1. symbol": "D0A.FRK",
		"2. name": "DADA NEXUS LTD ADS",
		"3. type": "Equity",
		"4. region": "Frankfurt",
		"5. marketOpen": "08:00",
		"6. marketClose": "20:00",
		"7. timezone": "UTC+02",
		"8. currency": "EUR",
		"9. matchScore": "0.3333",
	},
	{
		"1. symbol": "D0D.FRK",
		"2. name": "DICKER DATA LTD",
		"3. type": "Equity",
		"4. region": "Frankfurt",
		"5. marketOpen": "08:00",
		"6. marketClose": "20:00",
		"7. timezone": "UTC+02",
		"8. currency": "EUR",
		"9. matchScore": "0.3333",
	},
	{
		"1. symbol": "D0E.FRK",
		"2. name": "FRANCHETTI S.P.A.",
		"3. type": "Equity",
		"4. region": "Frankfurt",
		"5. marketOpen": "08:00",
		"6. marketClose": "20:00",
		"7. timezone": "UTC+02",
		"8. currency": "EUR",
		"9. matchScore": "0.3333",
	},
	{
		"1. symbol": "D0T.FRK",
		"2. name": "LEGIBLE INC.",
		"3. type": "Equity",
		"4. region": "Frankfurt",
		"5. marketOpen": "08:00",
		"6. marketClose": "20:00",
		"7. timezone": "UTC+02",
		"8. currency": "EUR",
		"9. matchScore": "0.3333",
	},
	{
		"1. symbol": "D1DG34.SAO",
		"2. name": "Datadog",
		"3. type": "Equity",
		"4. region": "Brazil/Sao Paolo",
		"5. marketOpen": "10:00",
		"6. marketClose": "17:30",
		"7. timezone": "UTC-03",
		"8. currency": "BRL",
		"9. matchScore": "0.2500",
	},
	{
		"1. symbol": "D1EL34.SAO",
		"2. name": "Dell Technologies Inc.",
		"3. type": "Equity",
		"4. region": "Brazil/Sao Paolo",
		"5. marketOpen": "10:00",
		"6. marketClose": "17:30",
		"7. timezone": "UTC-03",
		"8. currency": "BRL",
		"9. matchScore": "0.2000",
	},
	{
		"1. symbol": "D1EX34.SAO",
		"2. name": "DexCom Inc.",
		"3. type": "Equity",
		"4. region": "Brazil/Sao Paolo",
		"5. marketOpen": "10:00",
		"6. marketClose": "17:30",
		"7. timezone": "UTC-03",
		"8. currency": "BRL",
		"9. matchScore": "0.2000",
	},
];
